SELECT apt.supplier_code,
apt.supplier_id_erp,
apt.customer_code,
supio.fiscal_year,
supio.accounting_period,
supio.vendor_id,
supio.rna_vendor_name,
supio.year_quarter,
supio.supplier_id,
supio.location,
supio.diversity_attributes,
supio.city,
supio.state,
supio.postalcode,
supio.country,
supio.is_mbe,
supio.is_wbe,
supio.is_small,
supio.is_wosb,
supio.is_edwosb,
supio.is_dbe,
supio.is_sdb,
supio.is_self_sdb,
supio.is_8a,
supio.is_hub,
supio.is_vet,
supio.is_sdvet,
supio.is_hbcu,
supio.is_ability_one,
supio.is_disabled,
supio.is_anc_indian_tribe,
supio.is_acdbe,
supio.is_lgbt,
supio.supplierio_ethnicity,
supio.primary_diversity_type,
supio.small_business,
supio.diverse_and_small,
supio.start_date,
supio.end_date

FROM db_nam_supplier_io.msp_or_nam_supplier_io_derv_supplier_diversity supio
JOIN db_nam_aptus.msp_slsfrc_nam_aptus_derv_vms_join_unique apt on supio.vendor_id=apt.supplier_id_erp;
